version: '3'
services:
  
  web-vue:
    hostname: web-vue
    build: .
    environment:
      process.env.VUE_APP_RUTA_API: "http://0.0.0.0:5000"
      
    links:
      - "mybasedatos:json-server"  
    command: npm run serve
    ports:
      - "8086:8086"
    depends_on:
      - mybasedatos
    networks:
      conexion_networks:
        aliases:
          - conexion_bd
          
  mybasedatos:
    hostname: mybasedatos
    build: . 
    command: Set-ExecutionPolicy -Scope CurrentUser unrestricted
    command: json-server -H 0.0.0.0 -p 5000 --watch database/db.json
    ports:
      - "5000:5000"
    networks:
     conexion_networks:
       aliases:
        - conexion2_bd
     
networks:
   conexion_networks:
     name: conexion_net
     driver: bridge
     ipam:
       driver: default
        
   
